### ISSUE TITLE
Scrolling inside visualiser scrolls entire page

### ISSUE THREAD

**Issue by gunnnnii** [mattpocock/xstate-catalogue#53] opened 2021-05-29 11:48 UTC
I'm seeing an issue where the whole page scrolls as well when scrolling inside the visualiser. The recording is in Brave but this also happened in Safari and Chrome.

https://www.loom.com/share/d13e871bddcc44abb6b77160798192ea

**Comment by mattpocock** [comment] 2021-06-01 07:34
Closing as duplicate of #7

**Closed by mattpocock** 2021-06-01 07:34 UTC
